[package]
name = "llm_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"  # C FFI용 라이브러리
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["staticlib"]   # 정적 라이브러리 생성
path = "src/lib.rs"          # 이 줄이 있으면 위치를 명시적으로 보장
